# Generated by Django 5.1.4 on 2025-04-26 07:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blood_request', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='acceptbloodrequest',
            name='request_accept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accepted_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='acceptbloodrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accept_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blood_request', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='acceptbloodrequest',
            name='request_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to='blood_request.bloodrequest'),
        ),
        migrations.AlterUniqueTogether(
            name='acceptbloodrequest',
            unique_together={('user', 'request_user')},
        ),
    ]
