# Generated by Django 5.1.7 on 2025-03-13 02:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blood_request', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AcceptRequest',
            new_name='AcceptBloodRequest',
        ),
    ]
