# Generated by Django 5.1.7 on 2025-03-13 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blood_request', '0003_rename_request_acceptbloodrequest_request_accept'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodrequest',
            name='email',
        ),
    ]
