# Generated by Django 5.1.7 on 2025-03-13 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_request', '0008_alter_acceptbloodrequest_status_receivedblood'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivedblood',
            name='blood_request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_blood', to='blood_request.bloodrequest'),
        ),
    ]
