# Generated by Django 5.1.7 on 2025-03-13 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_request', '0010_alter_acceptbloodrequest_request_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receivedblood',
            name='blood_request',
        ),
        migrations.AddField(
            model_name='receivedblood',
            name='blood_post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='blood_post', to='blood_request.bloodrequest'),
            preserve_default=False,
        ),
    ]
