# Generated by Django 5.1.7 on 2025-03-13 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blood_request', '0011_remove_receivedblood_blood_request_and_more'),
    ]

    operations = [
    ]
