# Generated by Django 5.1.7 on 2025-03-13 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_request', '0016_alter_receivedblood_blood_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivedblood',
            name='accept_request',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='received_blood', to='blood_request.acceptbloodrequest'),
            preserve_default=False,
        ),
    ]
