# Generated by Django 5.1.7 on 2025-03-13 07:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blood_request', '0017_receivedblood_accept_request'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='acceptbloodrequest',
            unique_together={('user', 'request_accept')},
        ),
    ]
