# Generated by Django 5.1.7 on 2025-03-13 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blood_request', '0018_alter_acceptbloodrequest_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acceptbloodrequest',
            old_name='status',
            new_name='donation_status',
        ),
        migrations.RenameField(
            model_name='receivedblood',
            old_name='status',
            new_name='received_status',
        ),
    ]
