# Generated by Django 5.1.7 on 2025-04-25 10:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_request', '0019_rename_status_acceptbloodrequest_donation_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='date',
            field=models.DateField(),
        ),
    ]
