# Generated by Django 5.1.7 on 2025-04-25 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blood_request', '0020_bloodrequest_created_at_bloodrequest_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bloodrequest',
            old_name='address',
            new_name='hospital_address',
        ),
        migrations.RenameField(
            model_name='bloodrequest',
            old_name='city',
            new_name='hospital_name',
        ),
    ]
