# Generated by Django 5.1.7 on 2025-04-25 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_request', '0021_rename_address_bloodrequest_hospital_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='required_units',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
