# Generated by Django 5.1.4 on 2025-04-25 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_request', '0022_bloodrequest_required_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='urgency_level',
            field=models.CharField(choices=[('normal', 'Normal'), ('urgent', 'Urgent'), ('critical', 'Critical')], default='normal', max_length=10),
        ),
    ]
