# Generated by Django 5.1.4 on 2025-04-25 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_request', '0023_bloodrequest_urgency_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='post_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('completed', 'completed'), ('cancelled', 'cancelled')], default='pending', max_length=10),
        ),
    ]
