# Generated by Django 5.1.4 on 2025-04-25 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blood_request', '0024_bloodrequest_post_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bloodrequest',
            old_name='post_status',
            new_name='status',
        ),
    ]
