# Generated by Django 5.1.7 on 2025-03-14 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='user_blood_group',
            field=models.CharField(choices=[('O+', 'O-'), ('A+', 'A-'), ('B+', 'B-'), ('AB+', 'AB-')], default='A+', max_length=3),
            preserve_default=False,
        ),
    ]
