# Generated by Django 5.1.7 on 2025-03-14 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userdetails_user_blood_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='user_blood_group',
        ),
        migrations.AddField(
            model_name='userdetails',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], default='A+', max_length=3),
            preserve_default=False,
        ),
    ]
